language: cpp
sudo: true

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cat /etc/group
  - fgrep -qw 1003 /etc/group || sudo addgroup --gid 1003 test
  - fgrep -qw 1004 /etc/group || sudo addgroup --gid 1004 group1
  - fgrep -qw 1005 /etc/group || sudo addgroup --gid 1005 group2
  - fgrep -qw 1006 /etc/group || sudo addgroup --gid 1006 group3
  - fgrep -qw 1007 /etc/group || sudo addgroup --gid 1007 group4
  - fgrep -qw 1008 /etc/group || sudo addgroup --gid 1008 group5
  - fgrep -qw 2002 /etc/passwd || sudo adduser --home /home/test --shell /usr/bin/mysecureshell --uid 2002 --gid 1003 --disabled-password --gecos "" test
  - fgrep -qw 2003 /etc/passwd || sudo adduser --home /home/test2 --shell /usr/bin/mysecureshell --uid 2003 --gid 1003 --disabled-password --gecos "" test2
  - echo 'test:test' | sudo chpasswd
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libacl1-dev libgnutls28-dev; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 && brew link --force llvm35; fi

before_script:
  - travis_retry ./configure
#  - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure; fi

script:
  - sudo make install
  - cd tests
  - sudo -E `which mvn` clean package

#after_success:
#  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master
    - /^issue\d+/
    - /^v\d+\./

notifications:
  email: false

env:
  global:
    - LANG="en_US.UTF-8"
    - serverHost="localhost"
    - serverUser="test"
    - serverPassword="test"

os:
  - linux
#  - osx
